# Example configuration for a standalone subscriber
#
# It's possible to run only the subscriber. Then the configuration has only a
# section for the subscriber. And maybe another one for the client.

# The subscriber section must define:
#
# - statedir: the directory where the subcriber's data will be stored
# - http: where the subscriber listens to (a unix socket or a host/port)
# - urlbase: the base url users will use to reach the subscriber
# - quota: if defined, it will limit the disk usage
# - maxusers: if defined, it will limit the number of users
# - login: if true, users will need to authenticate
# - register: if true, users will be able to register
#
[subscriber]
statedir = "_caterva2/sub"
#http = "_caterva2/sub/uvicorn.socket"
http = "localhost:8002"
urlbase = "http://localhost:8002"
quota = "10G"
maxusers = 5
login = true   # users need to authenticate
register = true  # allow users to register

# The client section defines the credentials for the client to authenticate
# against the subscriber.
[client]
username = ""
password = ""
